### ISSUE TITLE
关于featuremap可视化生成是黑色的

### ISSUE THREAD

**Issue by sksunkui** [zhangjingcode/RadiomicsFeatureVisualization#4]
作者你好，我之前用过你的代码去生成可视化图像，但是有一段时间没用了之后，我发现再次去弄生成的热图是黑色的，不知道怎么样可以解决呢？

**Comment by zhangjingcode** [comment]
感谢您的使用！首先我在前一段时间进行过一些改动，至于您现在的问题需要确认一下代码和特征是否和之前一样？还有就是计算特征图时的kernel 半径是否太大太小。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sksunkui ***@***.***&gt;
发送时间: 2022年7月28日 16:00
收件人: zhangjingcode/RadiomicsFeatureVisualization ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangjingcode/RadiomicsFeatureVisualization] 关于featuremap可视化生成是黑色的 (Issue #4)





 
作者你好，我之前用过你的代码去生成可视化图像，但是有一段时间没用了之后，我发现再次去弄生成的热图是黑色的，不知道怎么样可以解决呢？

**Comment by sksunkui** [comment]
> 

谢谢您的回复，是这样的，我保存了您改动之前的代码和改动后的代码。我都分别重新做了一下，按照您给的示例文件，但是生成的热图是黑色的，colorbar是正常的，但是mask那个热图是黑色的。。。我也不清楚哪里出现了错误。不知道您方便提供一下联系方式吗？我还有一些问题想咨询一下您。

**Comment by sksunkui** [comment]
谢谢您的回复，是这样的，我保存了您改动之前的代码和改动后的代码。我都分别重新做了一下，按照您给的示例文件，但是生成的热图是黑色的，colorbar是正常的，但是mask那个热图是黑色的。。。我也不清楚哪里出现了错误。不知道您方便提供一下联系方式吗？我还有一些问题想咨询一下您。

**Comment by zhangjingcode** [comment]
你可以加我微信17317824554



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sksunkui ***@***.***&gt;
发送时间: 2022年7月29日 12:58
收件人: zhangjingcode/RadiomicsFeatureVisualization ***@***.***&gt;
抄送: zhangjingcode ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zhangjingcode/RadiomicsFeatureVisualization] 关于featuremap可视化生成是黑色的 (Issue #4)





 
谢谢您的回复，是这样的，我保存了您改动之前的代码和改动后的代码。我都分别重新做了一下，按照您给的示例文件，但是生成的热图是黑色的，colorbar是正常的，但是mask那个热图是黑色的。。。我也不清楚哪里出现了错误。不知道您方便提供一下联系方式吗？我还有一些问题想咨询一下您。

**Comment by JoannaWHN** [comment]
Debug:

FeatureMapShow.py
    def GenerarionFeatureROI(self):更改为
      feature_roi[np.min(x):np.min(x) + self.original_feature_map_array.shape[0],np.min(y):np.min(y) + self.original_feature_map_array.shape[1],np.min(z):np.min(z) +self.original_feature_map_array.shape[2]]= self.original_feature_map_array
