### ISSUE TITLE
FeatureMapByClass.py运行报错

### ISSUE THREAD

**Issue by 188-99** [zhangjingcode/RadiomicsFeatureVisualization#6]
作者您好，我运行FeatureMapByClass.py文件是总是提醒引用错误，似乎是SKMRradiomics中__init__中出现循环引用，按照搜索的方法瞎改一通，也总是报错，提醒no module named SKMRradiomics之类的。
打扰了，期待您的回复。

**Comment by zhangjingcode** [comment]
您可以试着把SKMRRadimics改成Radiomics库试试，SKMRRadimics这里我只是额外做了滤波器的保存。





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 188-99 ***@***.***&gt;
发送时间: 2023年3月16日 16:04
收件人: zhangjingcode/RadiomicsFeatureVisualization ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [zhangjingcode/RadiomicsFeatureVisualization] FeatureMapByClass.py运行报错 (Issue #6)





 
作者您好，我运行FeatureMapByClass.py文件是总是提醒引用错误，似乎是SKMRradiomics中__init__中出现循环引用，按照搜索的方法瞎改一通，也总是报错，提醒no module named SKMRradiomics之类的。
 打扰了，期待您的回复。

**Comment by 188-99** [comment]
万分感谢您的及时回复，我来来试试您说的方法。

**Comment by Spinexiang** [comment]
I think I'm having the same issue, running FeatureMapByClass.py is having a circular reference issue,
```
Error loading C extensions
Traceback (most recent call last):
  File "E:\Code\RadiomicsFeatureVisualization\SKMRradiomics\__init__.py", line 273, in <module>
    from . import _cmatrices as cMatrices  # noqa: F401
ImportError: cannot import name '_cmatrices' from partially initialized module 'SKMRradiomics' (most likely due to a circular import) (E:\Code\RadiomicsFeatureVisualization\SKMRradiomics\__init__.py)
Traceback (most recent call last):
  File "E:\Code\RadiomicsFeatureVisualization\FeatureMapByClass.py", line 24, in <module>
    from SKMRradiomics import featureextractor
  File "E:\Code\RadiomicsFeatureVisualization\SKMRradiomics\__init__.py", line 284, in <module>
    raise e
  File "E:\Code\RadiomicsFeatureVisualization\SKMRradiomics\__init__.py", line 273, in <module>
    from . import _cmatrices as cMatrices  # noqa: F401
ImportError: cannot import name '_cmatrices' from partially initialized module 'SKMRradiomics' (most likely due to a circular import) (E:\Code\RadiomicsFeatureVisualization\SKMRradiomics\__init__.py)
``` 

And I changed the import part as the author mentioned

Then, there show as follow:
```
Traceback (most recent call last):
  File "E:\Code\RadiomicsFeatureVisualization\FeatureMapByClass.py", line 292, in <module>
    main()
  File "E:\Code\RadiomicsFeatureVisualization\FeatureMapByClass.py", line 281, in main
    feature_mapper.generate_feature_map(str(img_path), str(roi_path), 1, features_name_list, str(store_path))
  File "E:\Code\RadiomicsFeatureVisualization\FeatureMapByClass.py", line 219, in generate_feature_map
    extractor = featureextractor.RadiomicsFeaturesExtractor(parameter_path, self.store_path, **setting_dict)
AttributeError: module 'radiomics.featureextractor' has no attribute 'RadiomicsFeaturesExtractor'
``` 
Look into the code of featureextractor, actually there is the class named 'RadiomicsFeatureExtractor'

So I think may be version update issue.

**Comment by cozmiiika** [comment]
这个问题是由于项目中CMake生成文件与运行环境以及操作系统不匹配导致的
\_cmatrices.cp37-win_amd64.pyd 对应python3.7，windows操作系统

解决方案：
1. 新建conda环境
	conda create --name radiomics_vis python=3.7
	conda activate radiomics_vis
2. **实测numpy版本高了或低了都会报错，且CMake文件需要对应Numpy版本，matplotlib和pandas都有numpy的依赖，所以先安装包numpy, matplotlib,  pandas**
	经测试可以运行的版本：
	numpy\==1.16.0
	pandas\==1.0.0
	matplotlib\==3.0.0
	\* 用matplotlib 3.0.0的话，记得把FeatureMapShow里保存格式改成png
3. 安装对应版本的radiomics包（版本号在SKMRadiomics/\_version.py里）
	pip3 install pyradiomics\==2.1.2
	若安装时卡在building wheel for simpleitk，可以停止安装并先执行pip3 install simpleitk\==1.2.4
4. 安装好pyradiomics包之后，进入对应conda环境的site-packages目录下，找到radiomics文件夹，文件夹内部有CMake生成的对应的.pyd(win)或.so(linux)文件
5. 将SKMRadiomics文件夹中原有的两个.pyd文件删除，radiomics文件夹中的两个.pyd或.so文件拷过来
6. 然后在新建的conda环境中就可以正常导入并使用SKMRadiomics了

测试运行结果：

<img width="1442" height="1242" alt="Image" src="https://github.com/user-attachments/assets/433c53f3-1d7c-4fe3-b2d0-6ca9c773a378" />

（其实换成在原来的环境直接加载radiomics包也可以用，但是跑出来的结果会略微不一致）
原环境使用radiomics3.1.0 ：

<img width="456" height="357" alt="Image" src="https://github.com/user-attachments/assets/c965f154-a4b2-4b20-b33c-2b3a969c6f1f" />

示例可视化结果：

<img width="381" height="312" alt="Image" src="https://github.com/user-attachments/assets/6331b721-b238-496f-aaf5-b8de808de705" />
